### ISSUE TITLE
Is there a way to indicate that I don't want the code to be changed per line?

### ISSUE THREAD

**Issue by EduardoRT** [ben-eb/postcss-zindex#2]
Hi! I'm ussing css nano and I can't deactivate this plugin which is incorrectly changing my z-index;

I'm disabling it like this

```
options: {
            zindex            : false,
            safe              : true,
            discardDuplicates : false,
          }
```

But there's just one part of my code where it's misbehaving, is there a way to indicate that I don't want to run any optimization in that line? Something like:

```
h1 {
    z-index: 1000;  /*DONT CHANGE*/
}
```

Thanks

**Comment by TrySound** [comment]
@EduardoRT Nope.) z-index not so big thing, so you can save all of them.
And also safe mode disables zindex.

**Comment by ben-eb** [comment]
I don't think we can support control comments, due to the way that comment removal has to operate first. It's fine to disable the optimisation completely like you are doing.

The only way I could suggest that you might be able to get this done is via using PostCSS and loading postcss-zindex through [postcss-plugin-context](https://github.com/postcss/postcss-plugin-context). That way you could set a context where you apply the `z-index` transforms, and then exclude your `h1` rule from that context:

```css
div {
  z-index: 100;
}

@context zindex {
  h1 {
    z-index: 1000;
  }
}
```

Would output:

```css
div{z-index:1}h1{z-index:1000}
```
